name: CI/CD Test

on:
  push:
    branches: ["main"]

jobs:
  # Name of the job/test
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Build/Restore Unit Project
        run: cd unit-test && dotnet build
      - name: Start server
        run: cd formbridge-main/server && nohup dotnet run &
      - name: Run unit-test
        run: cd unit-test && dotnet test
  api_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install Newman
        run: npm install -g newman
      - name: Install dotnet project dependencies
        run: cd formbridge-main/server && dotnet restore
      - name: Build
        run: cd formbridge-main/server && dotnet build
      - name: Start Server
        run: cd formbridge-main/server && nohup dotnet run &
      - name: Run API-Tests
        run: newman run api-test/API-test.postman_collection.json -e api-test/API-test-Environment.postman_environment.json --bail

  gui_tests:
    runs-on: ubuntu-latest
    needs: api_tests # Kör endast om api testerna går igenom
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Install dotnet project dependencies
        run: cd E2ETesting-main && dotnet restore
      - name: Build/Restore Playwright Project
        run: cd E2ETesting-main && dotnet build
      - name: Ensure browsers are installed
        run: cd E2ETesting-main && pwsh bin/Debug/net8.0/playwright.ps1 install --with-deps
      - name: Start server
        run: cd formbridge-main/server && nohup dotnet run &
      - name: Start client
        run: |
          cd formbridge-main/client
          nohup npm install
          nohup npm run dev > react-server.log 2>&1 &
          sleep 5
          cat react-server.log || true
      - name: Test frontend availability
        run: |
          for i in {1..30}; do
            curl --fail http://localhost:5173/ && echo "Frontend is responding!" && exit 0
            echo "Waiting for frontend..."
            sleep 2
          done
          echo "Frontend did not start!" && exit 1
      - name: Install wait-on
        run: npm install -g wait-on
      - name: Wait for frontend to be ready
        run: wait-on http://localhost:5173
      - name: Run GUI-tests
        run: cd E2ETesting-main && dotnet test
